### ISSUE TITLE
Trovo RTMP

### ISSUE THREAD

**Issue by Patraskon** [sandyh90/rockstream-streaming-relay#7]
RTMP Stream Key length on Trovo exceeds 255 characters limit

**Comment by sandyh90** [comment]
Hi @Patraskon, I'm sorry about that because it causes by validation that limits character length and I don't know exactly how long the stream key is on each streaming provider, but you can quickly fix this issue by changing the limit value on validation and migration database, I will give you step process to fix this issue.

Web folder located:
- Setup Method: **C:\Users\<your_pc_username>\AppData\Local\Programs\rockstream-stream-repeater\resources**
- Portable Method: Go to **resources**

1. Step one,  Change the validation limit value in Ingest Stream Destination on function **"add_output_dest"** and **"edit_output_dest"**.

File: **"web/app/Http/Controllers/IngestDestinationController.php"**

Example:
```php
$validator = Validator::make(
                $request->all(),
                [
                    'name_output_dest' => 'required|string|max:255',
                    'platform_output_dest' => [
                        'required',
                        Rule::in(array_column(ServicesCore::getServices(), 'id'))
                    ],
                    'select_endpoint_server' => $request->filled('rtmp_output_server') ? 'prohibited|nullable|string|max:255|starts_with:rtmp://,rtmps://' : 'required|string|max:255|starts_with:rtmp://,rtmps://',
                    'rtmp_output_server' => $request->filled('select_endpoint_server') ? 'prohibited|nullable|string|max:255|starts_with:rtmp://,rtmps://' : 'required|string|max:255|starts_with:rtmp://,rtmps://',
                    'rtmp_stream_key' => empty($check_stream->ingest_destination_data()->first()->key_stream_dest) ? 'required|string|max:650' : ($check_stream->ingest_destination_data()->first()->key_stream_dest != $request->rtmp_stream_key ? 'required|string|max:650' : 'required|unique:stream_ingest_dest,key_stream_dest|string|max:650'),
                    'status_output_dest' => 'required|boolean'
                ]
            );
```

2. Step two, Change migration for Ingest Stream Destination.

File: **"web/database/migrations/2021_11_21_034813_create_stream_repeater_dest_table.php"**

Example:
```php
public function up()
    {
        Schema::create('stream_ingest_dest', function (Blueprint $table) {
            $table->id();
            $table->foreignId('input_stream_id')->nullable()->constrained('input_stream')->cascadeOnDelete()->cascadeOnUpdate();
            $table->foreignId('user_id')->nullable()->constrained('users')->cascadeOnDelete()->cascadeOnUpdate();
            $table->string('name_stream_dest');
            $table->string('platform_dest');
            $table->string('url_stream_dest');
            $table->string('key_stream_dest', 650);  /* or you can use $table->text('key_stream_dest'); */
            $table->boolean('active_stream_dest');
            $table->timestamps();
        });
    }
```

3. Step three, I suggested you refresh the database using **Reset To Factory** on Interface Settings in Misc Tab

![Screenshot 2022-07-08 130850](https://user-images.githubusercontent.com/30236529/177928095-63bef26d-8047-420c-bc1e-1a3c54d1fd60.png)

**Comment by sandyh90** [comment]
If you have another question that is related to this issue you can open it again this issue 😉
